CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 --master_port=34321 train_ctx2instruct.py \
    --model_name_or_path EleutherAI/polyglot-ko-1.3b \
    --data_path data/unified_instruction_nc.json \
    --fp16 \
    --torch_dtype float16 \
    --output_dir experiments/poly1.3b-res2inst_b4_ga8_g8_l1k \
    --run_name poly1.3b-res2inst_b4_ga8_g8_l1k \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 8 \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate 5e-5 \
    --weight_decay 0. \
    --warmup_steps 100 \
    --block_size 1024 \
    --lr_scheduler_type "cosine" \
    --logging_strategy='steps' \
    --logging_steps 1 \
    --deepspeed ds_zero3-nooffload.json