CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun \
    --nproc_per_node=4 --master_port=34323 train_dapt.py \
    --model_name_or_path EleutherAI/polyglot-ko-1.3b \
    --data_path /home/repos/ElementGPT/data/사전학습_데이터/output_data/combined.json \
    --optim adafactor \
    --fp16 \
    --torch_dtype float16 \
    --output_dir experiments/poly1.3b-clean_b3_ga5_g8_l1k_lr2e5 \
    --run_name poly1.3b-clean_b3_ga5_g8_l1k_lr2e5 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 5 \
    --preprocessing_num_workers 6 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --lr_scheduler_type "cosine" \
    --weight_decay 0. \
    --warmup_ratio 0.1 \
    --logging_steps 2 \
    --block_size 256 \
    --model_max_length 256 \
    --deepspeed ds_zero3-nooffload.json \
    --low_cpu_mem_usage